---
name: Check inclusive language

on:
  pull_request:
    types: ['opened']

jobs:
  check-inclusive-language:
    name: Check inclusive language
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: woke
        run: |
          curl -sSfL https://git.io/getwoke | bash -s -- -b /usr/local/bin
          woke -c https://via.vmw.com/its-woke-rules -o github-actions --exit-1-on-failure
