---
name: Check inclusive language

on:
  pull_request_target:
    types: ['opened']

jobs:
  check-inclusive-language:
    name: Check inclusive language
    runs-on: ubuntu-latest
    steps:
      - name: Install Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: woke
        run: |
          go install github.com/get-woke/woke@latest
          woke
