---
name: Check inclusive language

on:
 pull_request:
   types: ['opened']

jobs:
  check-inclusive-language:
    name: Check inclusive language
    runs-on: ubuntu-latest
    uses: aaronshurley/test-woke/.github/workflows/inclusive-language-check.yml@main
